modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="naruto_universe"
version="${file.jarVersion}"
displayName="Naruto Universe"
logoFile="naruto_universe.png"
credits=""
authors="RadonCoding"

description='''
This mod adds stuff from naruto to minecraft
'''

[[dependencies.naruto_universe]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naruto_universe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
